### ISSUE TITLE
[Task list] Classes to be tested

### ISSUE THREAD

**Issue by Raqkkkkk** [sherwinokhowat/Group-Formation-System#88]
This is a list for all classes that still isn't tested. Feel free to add new classes to this list.
## Use cases
- [x] #102
- [x] #126
- [x] #122
- [x] #127
- [x] #90
- [x] #89
- [x] #113
- [x] #93
- [x] #110
- [x] #125
- [x] Logout (increase coverage) (#144)
- [x] Accept application (increase coverage) (#144)
- [x] Get application
- [x] Reject application (increase coverage) (#144)
- [x] Delete project
- [x] Delete users (increase coverage)
- [x] #148 
- [x] Remove users from project

## View models
- [ ] Add project panel
- [ ] Display project application
- [ ] Edit profile
- [ ] Login panel
- [ ] Switch view button panel
- [ ] View user

## Database
- [x] Repositories

**Comment by Justinfan591** [comment]
Why do we have a Search project by ID use case? We do not have any method for User to know the ID though.

**Comment by Justinfan591** [comment]
Should we delete the use case? There is not much use for it anyways.

**Comment by cecexyzhang** [comment]
> Why do we have a Search project by ID use case? We do not have any method for User to know the ID though.

I think this is not user-facing. It could be used for database operations.

**Comment by cecexyzhang** [comment]
I will add tests for two use cases. #126 and #127

**Comment by sherwinokhowat** [comment]
> > Why do we have a Search project by ID use case? We do not have any method for User to know the ID though.
> 
> I think this is not user-facing. It could be used for database operations.

I don't think it makes sense to use it in database operations. The repositories already include methods for getting users and projects by their IDs. I believe we originally planned to include this use case, but eventually realized that it wasn't practical and thus discontinued it.

**Comment by Raqkkkkk** [comment]
updated with most recent test coverage data
